<?xml version="1.0" encoding="utf-8"?><Database Name="MarathonSkills2015" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=MarathonSkills2015;Integrated Security=True" SettingsObjectName="MarathonSkills2015_TO6.Properties.Settings" SettingsPropertyName="db_marathonskills2015_7ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Charity" Member="Charities">
    <Type Name="Charity">
      <Column Name="CharityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CharityName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CharityDescription" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="CharityLogo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Charity_Registration" Member="Registrations" ThisKey="CharityId" OtherKey="CharityId" Type="Registration" />
    </Type>
  </Table>
  <Table Name="dbo.Volunteer" Member="Volunteers">
    <Type Name="Volunteer">
      <Column Name="VolunteerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Country_Volunteer" Member="Country" ThisKey="CountryCode" OtherKey="CountryCode" Type="Country" IsForeignKey="true" />
      <Association Name="Gender_Volunteer" Member="Gender1" ThisKey="Gender" OtherKey="Gender1" Type="Gender" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryCode" Type="System.String" DbType="NChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CountryFlag" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Country_Volunteer" Member="Volunteers" ThisKey="CountryCode" OtherKey="CountryCode" Type="Volunteer" />
      <Association Name="Country_Marathon" Member="Marathons" ThisKey="CountryCode" OtherKey="CountryCode" Type="Marathon" />
      <Association Name="Country_Runner" Member="Runners" ThisKey="CountryCode" OtherKey="CountryCode" Type="Runner" />
    </Type>
  </Table>
  <Table Name="dbo.Distance" Member="Distances">
    <Type Name="Distance">
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Length" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Events">
    <Type Name="Event">
      <Column Name="EventId" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeId" Type="System.String" DbType="NChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="MarathonId" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="MaxParticipants" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Event_RegistrationEvent" Member="RegistrationEvents" ThisKey="EventId" OtherKey="EventId" Type="RegistrationEvent" />
      <Association Name="EventType_Event" Member="EventType" ThisKey="EventTypeId" OtherKey="EventTypeId" Type="EventType" IsForeignKey="true" />
      <Association Name="Marathon_Event" Member="Marathon" ThisKey="MarathonId" OtherKey="MarathonId" Type="Marathon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventType" Member="EventTypes">
    <Type Name="EventType">
      <Column Name="EventTypeId" Type="System.String" DbType="NChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTypeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="EventType_Event" Member="Events" ThisKey="EventTypeId" OtherKey="EventTypeId" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Gender" Member="Genders">
    <Type Name="Gender">
      <Column Name="Gender" Member="Gender1" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Gender_Volunteer" Member="Volunteers" ThisKey="Gender1" OtherKey="Gender" Type="Volunteer" />
      <Association Name="Gender_Runner" Member="Runners" ThisKey="Gender1" OtherKey="Gender" Type="Runner" />
    </Type>
  </Table>
  <Table Name="dbo.InteractiveMap" Member="InteractiveMaps">
    <Type Name="InteractiveMap">
      <Column Name="[Checkpoint]" Member="Checkpoint" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Landmark" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Facility" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Marathon" Member="Marathons">
    <Type Name="Marathon">
      <Column Name="MarathonId" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MarathonName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="YearHeld" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Marathon_Event" Member="Events" ThisKey="MarathonId" OtherKey="MarathonId" Type="Event" />
      <Association Name="Country_Marathon" Member="Country" ThisKey="CountryCode" OtherKey="CountryCode" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Position" Member="Positions">
    <Type Name="Position">
      <Column Name="PositionId" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PositionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PositionDescription" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PayPeriod" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Payrate" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="Position_Staff" Member="Staffs" ThisKey="PositionId" OtherKey="PositionId" Type="Staff" />
    </Type>
  </Table>
  <Table Name="dbo.RaceKitOption" Member="RaceKitOptions">
    <Type Name="RaceKitOption">
      <Column Name="RaceKitOptionId" Type="System.Char" DbType="NChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RaceKitOption" Member="RaceKitOption1" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="RaceKitOption_Registration" Member="Registrations" ThisKey="RaceKitOptionId" OtherKey="RaceKitOptionId" Type="Registration" />
    </Type>
  </Table>
  <Table Name="dbo.Registration" Member="Registrations">
    <Type Name="Registration">
      <Column Name="RegistrationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RunnerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RaceKitOptionId" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationStatusId" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="CharityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SponsorshipTarget" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="Registration_RegistrationEvent" Member="RegistrationEvents" ThisKey="RegistrationId" OtherKey="RegistrationId" Type="RegistrationEvent" />
      <Association Name="Registration_Sponsorship" Member="Sponsorships" ThisKey="RegistrationId" OtherKey="RegistrationId" Type="Sponsorship" />
      <Association Name="Charity_Registration" Member="Charity" ThisKey="CharityId" OtherKey="CharityId" Type="Charity" IsForeignKey="true" />
      <Association Name="RaceKitOption_Registration" Member="RaceKitOption" ThisKey="RaceKitOptionId" OtherKey="RaceKitOptionId" Type="RaceKitOption" IsForeignKey="true" />
      <Association Name="RegistrationStatus_Registration" Member="RegistrationStatus" ThisKey="RegistrationStatusId" OtherKey="RegistrationStatusId" Type="RegistrationStatus" IsForeignKey="true" />
      <Association Name="Runner_Registration" Member="Runner" ThisKey="RunnerId" OtherKey="RunnerId" Type="Runner" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegistrationEvent" Member="RegistrationEvents">
    <Type Name="RegistrationEvent">
      <Column Name="RegistrationEventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegistrationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventId" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="BibNumber" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RaceTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Event_RegistrationEvent" Member="Event" ThisKey="EventId" OtherKey="EventId" Type="Event" IsForeignKey="true" />
      <Association Name="Registration_RegistrationEvent" Member="Registration" ThisKey="RegistrationId" OtherKey="RegistrationId" Type="Registration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegistrationStatus" Member="RegistrationStatus">
    <Type Name="RegistrationStatus">
      <Column Name="RegistrationStatusId" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegistrationStatus" Member="RegistrationStatus1" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Association Name="RegistrationStatus_Registration" Member="Registrations" ThisKey="RegistrationStatusId" OtherKey="RegistrationStatusId" Type="Registration" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Char" DbType="NChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Runner" Member="Runners">
    <Type Name="Runner">
      <Column Name="RunnerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Association Name="Runner_Registration" Member="Registrations" ThisKey="RunnerId" OtherKey="RunnerId" Type="Registration" />
      <Association Name="Country_Runner" Member="Country" ThisKey="CountryCode" OtherKey="CountryCode" Type="Country" IsForeignKey="true" />
      <Association Name="Gender_Runner" Member="Gender1" ThisKey="Gender" OtherKey="Gender1" Type="Gender" IsForeignKey="true" />
      <Association Name="User_Runner" Member="User" ThisKey="Email" OtherKey="Email" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Speed" Member="Speeds">
    <Type Name="Speed">
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Speed" Member="Speed1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sponsorship" Member="Sponsorships">
    <Type Name="Sponsorship">
      <Column Name="SponsorshipId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SponsorName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="Registration_Sponsorship" Member="Registration" ThisKey="RegistrationId" OtherKey="RegistrationId" Type="Registration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="StaffId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PositionId" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Association Name="Staff_Timesheet" Member="Timesheets" ThisKey="StaffId" OtherKey="StaffId" Type="Timesheet" />
      <Association Name="Position_Staff" Member="Position" ThisKey="PositionId" OtherKey="PositionId" Type="Position" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Timesheet" Member="Timesheets">
    <Type Name="Timesheet">
      <Column Name="TimesheetId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StaffId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PayAmount" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="Staff_Timesheet" Member="Staff" ThisKey="StaffId" OtherKey="StaffId" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Association Name="User_Runner" Member="Runners" ThisKey="Email" OtherKey="Email" Type="Runner" />
    </Type>
  </Table>
</Database>